services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: file:./dev.db
    ports:
      - "3000:3000"
    volumes:
      - ./dev.db:/app/dev.db
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
    command: >
      sh -c "mkdir -p /app/public/uploads &&
      npx prisma db push &&
      npm run start:host"
