apiVersion: v1
kind: ConfigMap
metadata:
  name: lamaran-config
  namespace: lamaran
data:
  NODE_ENV: "production"
  DATABASE_URL: "file:./data/dev.db"
  NEXT_PUBLIC_BASE_URL: "https://undangan.example.com"
