apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lamaran-web
  namespace: lamaran
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - undangan.example.com
      secretName: lamaran-tls
  rules:
    - host: undangan.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lamaran-web
                port:
                  number: 80
