apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lamaran
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc-db.yaml
  - pvc-uploads.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
