apiVersion: v1
kind: Secret
metadata:
  name: lamaran-secret
  namespace: lamaran
type: Opaque
stringData:
  ADMIN_USERNAME: "ganti-admin"
  ADMIN_PASSWORD: "ganti-password-kuat"
  AUTH_SECRET: "ganti-dengan-random-secret-yang-panjang"
